#!/bin/bash

set -e

. $(dirname "$0")/constants.cfg

# usage: ./run_command_on_worker.sh <worker_id> <command>

WORKER_ADDRESS="WORKER_ADDRESS_$1"
WORKER_INTERNAL_ADDRESS="WORKER_INTERNAL_ADDRESS_$1"
COMMAND="${@:2}"

FULL_COMMAND="MASTER_INTERNAL_ADDRESS=$MASTER_INTERNAL_ADDRESS WORKER_INTERNAL_ADDRESS=${!WORKER_INTERNAL_ADDRESS} $COMMAND"

echo -e "\n🏭 Run '$COMMAND' on WORKER_$1 at '${!WORKER_ADDRESS}'"
ssh -i $SSH_KEY_PATH $SSH_USERNAME@${!WORKER_ADDRESS} "$FULL_COMMAND"

exit 0