version: "2"

networks:
  default:
    external:
      name: lambda-network

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg12
    container_name: timescaledb
    ports:
      - 5432:5432
    volumes:
      - timescaledb-data:/var/lib/postgresql/data
      - ./sql:/home/sql
    environment:
      POSTGRES_PASSWORD: 8zr7E3SV

  redis:
    image: docker.io/bitnami/redis:6.2
    container_name: redis
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
      - REDIS_PASSWORD=8zr7E3SV
    ports:
      - "6379:6379"
    volumes:
      - "redis-data:/bitnami/redis/data"

volumes:
  timescaledb-data:
    external: true
  redis-data:
    external: true
