{
 "title": "Lametro Bus",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "current bus location (with velocity km/h)",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT DISTINCT ON (bus_id)\n  \"timestamp\" AS \"time\",\n  bus_id AS \"bus_id\",\n  latitude AS \"latitude\",\n  longitude AS \"longitude\",\n  velocity * 3.6 AS \"velocity\"\nFROM bus_arrival\nWHERE\n  $__timeFilter(\"timestamp\")\nGROUP BY \"timestamp\", bus_id, latitude, longitude, velocity\nORDER BY bus_id, \"time\" DESC"
    }
   ]
  },
  {
   "title": "system latency",
   "type": "gauge",
   "description": "latency due to system processing",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT percentile_cont(0.5) WITHIN GROUP (ORDER BY EXTRACT(MILLISECONDS FROM (\"inserted_time\" - \"req_time\"))) AS p50\nFROM bus_arrival\nWHERE $__timeFilter(\"timestamp\")"
    },
    {
     "rawSql": "SELECT percentile_cont(0.90) WITHIN GROUP (ORDER BY EXTRACT(MILLISECONDS FROM (\"inserted_time\" - \"req_time\"))) AS p90\nFROM bus_arrival\nWHERE $__timeFilter(\"timestamp\")"
    },
    {
     "rawSql": "SELECT percentile_cont(0.99) WITHIN GROUP (ORDER BY EXTRACT(MILLISECONDS FROM (\"inserted_time\" - \"req_time\"))) AS p99\nFROM bus_arrival\nWHERE $__timeFilter(\"timestamp\")"
    }
   ]
  },
  {
   "title": "overall latency",
   "type": "gauge",
   "description": "system latency plus network latency, bottle neck, ...",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT percentile_cont(0.50) WITHIN GROUP (ORDER BY EXTRACT(MILLISECONDS FROM (\"inserted_time\" - \"timestamp\"))) AS p50\nFROM bus_arrival\nWHERE $__timeFilter(\"timestamp\")"
    },
    {
     "rawSql": "SELECT percentile_cont(0.90) WITHIN GROUP (ORDER BY EXTRACT(MILLISECONDS FROM (\"inserted_time\" - \"timestamp\"))) AS p90\nFROM bus_arrival\nWHERE $__timeFilter(\"timestamp\")"
    },
    {
     "rawSql": "SELECT percentile_cont(0.99) WITHIN GROUP (ORDER BY EXTRACT(MILLISECONDS FROM (\"inserted_time\" - \"timestamp\"))) AS p99\nFROM bus_arrival\nWHERE $__timeFilter(\"timestamp\")"
    }
   ]
  },
  {
   "title": "route velocity (km/h)",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT ON (route_id, direction)\nroute_id, direction, velocity\nFROM bus_arrival\nWHERE $__timeFilter(\"timestamp\")\nGROUP BY route_id, direction, velocity, \"timestamp\"\nORDER BY route_id, direction, \"timestamp\" DESC"
    }
   ]
  },
  {
   "title": "arrival time prediction",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT *\nFROM (\n  SELECT\n    bus_id AS \"bus_id\",\n    stop_id AS \"stop_id\",\n    max((\"timestamp\" + make_interval(secs => seconds_till_meet))) AS \"arrival_time\"\n  FROM bus_arrival\n  WHERE $__timeFilter(\"timestamp\")\n  GROUP BY bus_id, stop_id\n) AS temp\nORDER BY bus_id, arrival_time"
    }
   ]
  }
 ]
}