version: "2"

networks:
  default:
    external:
      name: lambda-network

volumes:
  lambda-grafana-storage:
    external: true

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: "472:472"
    ports:
      - 3000:3000
    volumes:
      - lambda-grafana-storage:/var/lib/grafana
    environment:
      - TERM=linux
      - GF_INSTALL_PLUGINS=grafana-worldmap-panel
