version: "2"

networks:
  default:
    external:
      name: lambda-network

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg12
    container_name: timescaledb
    ports:
      - 5432:5432
    volumes:
      - timescaledb-data:/var/lib/postgresql/data
      - ./data:/home/data
      - ./sql:/home/sql
    environment:
      POSTGRES_PASSWORD: 8zr7E3SV

  redis:
    image: docker.io/bitnami/redis:6.2
    container_name: redis
    environment:
      # - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
      - REDIS_PASSWORD=8zr7E3SV
    ports:
      - "6379:6379"
    volumes:
      - "redis-data:/bitnami/redis/data"

  namenode:
    image: bde2020/hadoop-namenode:1.1.0-hadoop2.8-java8
    container_name: namenode
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://master:8020
    ports:
      - 50070:50070
      - 8020:8020
    volumes:
      - hdfs-namenode:/hadoop/dfs/name
      - ./data:/home/data

volumes:
  hdfs-namenode:
    external: true
  timescaledb-data:
    external: true
  redis-data:
    external: true
