version: "2"

networks:
  default:
    external:
      name: lambda-network

services:
  server:
    image: yandex/clickhouse-server:20.8
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
  client:
    image: yandex/clickhouse-client:20.8
    command: ["--host", "server"]
