version: "2"

networks:
  default:
    external:
      name: lambda-network

services:
  pyspark-notebook:
    image: jupyter/pyspark-notebook:spark-3.1.1
    container_name: pyspark-notebook
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./third-party-jars:/usr/local/spark/third-party-jars
      - ../storage/data:/home/data
    ports:
      - 8888:8888
      - 8081:8081
      - 7070:7070
    user: root
    environment:
      - GRANT_SUDO=yes
