version: "2"

networks:
  default:
    external:
      name: lambda-network

services:
  pyspark-notebook:
    image: lhvubtqn.azurecr.io/pyspark-notebook-with-third-party-jars:3.1.2-bin-hadoop3.2
    container_name: pyspark-notebook
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./third-party-jars:/usr/local/spark/third-party-jars
      - ../storage/data:/home/data
    ports:
      - 8888:8888
      - 8080:8080
      - 4040:4040
      - 4041:4041
      - 4042:4042
    user: root
    environment:
      - GRANT_SUDO=yes
