apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-data-disk
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  ports:
    - name: "9092"
      port: 9092
    - name: "29092"
      port: 29092
  selector:
    app: kafka