apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zookeeper-disk
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  ports:
    - name: "2181"
      port: 2181
  selector:
    app: zookeeper