apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  strategy: {}
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: zookeeper
          image: confluentinc/cp-zookeeper:6.0.0
          ports:
            - containerPort: 2181
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
          volumeMounts:
            - mountPath: "/var/lib/zookeeper/data"
              name: zookeeper-volume
              subPath: data
            - mountPath: "/var/lib/zookeeper/log"
              name: zookeeper-volume
              subPath: log
      restartPolicy: Always
      volumes:
        - name: zookeeper-volume
          persistentVolumeClaim:
            claimName: zookeeper-disk