version: "2"

networks:
  default:
    external:
      name: lambda-network

services:
  clickhouse:
    image: yandex/clickhouse-server:20.8
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
